### ISSUE TITLE
CI not compatible with ssh_cmd from HW2

### ISSUE THREAD

**Issue by AndreasMReumschuessel** [htwg-syslab-syso/syso-template#6]
Regarding: https://github.com/htwg-syslab-syso/htwg-syslab-syso.github.io/pull/90
In the description of HW2 it is mentioned that the command has to be like `ssh_cmd "echo Hello, World!"`.

1. The CI executes the command like this: 
`run '/home/anreumsc/mumm/syso-ws17-grp10/hw2/hw2.sh ssh_cmd echo 'Hello, World!''...`
which is different from the description and would result in a different parsing behaviour in the hw2.sh.

2. Even when the command itself is corrected to run the hw2.sh like in the description, the CI will hang-up and doesn't continue. This also happens to @hekrause. When using `ps -ax | grep qemu` you can see that the qemu process is stopped.

Will this be fixed until friday?

@steveeJ

**Comment by DonatJR** [comment]
@AndreasMReumschuessel can't help you with respect to the first point, but the second on is a result of running qemu as a background job. the reason is that qemu wants to read from stdin before it starts initializing the kernel, which is not possible for background jobs (have a look at https://unix.stackexchange.com/questions/36494/qemu-do-not-start-when-executed-in-background-inside-shell-script/36508#36508) - you can work around this by redirecting the input (i.e. ./hw2 qemu </dev/null &). be advised that redirecting to /dev/null will result in your kernel not being able to receive any input at all - we are not sure what a completely correct solution for this issue would look like (we opened an issue in our own repo with no conclusion as of yet)

@SWW13 regarding the qemu 'freeze': it seems we are not the only group with this issue

**Comment by steveeJ** [comment]
@AndreasMReumschuessel 

> The CI executes the command like this:
> run '/home/anreumsc/mumm/syso-ws17-grp10/hw2/hw2.sh ssh_cmd echo 'Hello, World!''...
> which is different from the description and would result in a different parsing behaviour in the hw2.sh.

The output emits the `"` which are in the file, but they are used by the command.

The CI Script uses:  https://github.com/htwg-syslab-syso/syso-template/blob/9a34c951fc7cd6d98bcdd0be4194963ebb395006/ci/run-test-labshell.sh#L74
Which looks very similar to the homework PR: [`ssh_cmd "echo Hello, World!"`](https://github.com/htwg-syslab-syso/htwg-syslab-syso.github.io/blob/c7809d4b8ae5a4cb2e96e8f8f29e1b47ac300ca8/src/Homework2/README.md#228)

with the subtle difference that `echo` will receive just one argument from the CI script and two arguments from the example.

> Even when the command itself is corrected to run the hw2.sh like in the description, the CI will hang-up and doesn't continue. This also happens to @hekrause. When using ps -ax | grep qemu you can see that the qemu process is stopped.

I can reproduce this and I find the suggestion by @DonatJR of adding `0</dev/null` is a viable workaround. However, it shouldn't be a part of your solution but instead live in the CI script. I will file a PR against the syso-template repository to fix this and a couple other issues.

**Comment by AndreasMReumschuessel** [comment]
@DonatJR Thank you for your help! After redirecting the stdin of qemu to `/dev/null`, it worked. And as you already said, there isn't any input recognized so I'm also not able to terminate qemu manually with the hotkey. I can only terminate the process with kill.
The first point got obsolete with the solution of the second one, so sorry for that.

Thanks a bunch!
